### ISSUE TITLE
Validar rut 0-0, 00-0, 000-0, etc

### ISSUE THREAD

**Issue by francovp** [devcarlos/RUTValidator#2]
La librería considera válido ruts como `0-0`,  `00-0`, `000-0` y así con más ceros como `0.000.000.000-0`.
No se si debería ser normal pero supongo que no.

**Comment by devcarlos** [comment]
Segun la normativa del SII son validos:

![E467900B-7F9D-4C62-ABC0-A7D5CDBEEFDD](https://user-images.githubusercontent.com/646364/72908820-c90e0180-3d14-11ea-9db1-70d135b20ce7.jpeg)
![B7A6E820-DA33-4BC6-B29B-C48BBCB9FEC7](https://user-images.githubusercontent.com/646364/72908842-cf9c7900-3d14-11ea-998a-003920f969c8.jpeg)

Por lo tanto la libreria esta funcionando bien.
